# Generated by Django 5.1.1 on 2024-09-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companhia',
            new_name='Curso',
        ),
        migrations.CreateModel(
            name='Coodenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('matricula', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Voo',
        ),
    ]
